/** Texture-atlas tile indices (8×8 grid, 16px each). Atlas art is generated in render/atlas.ts. */
export const TILE = {
  GRASS_TOP: 0,
  GRASS_SIDE: 1,
  DIRT: 2,
  STONE: 3,
  LOG_SIDE: 4,
  LOG_TOP: 5,
  PLANKS: 6,
  LEAVES: 7,
  COAL_ORE: 8,
  IRON_ORE: 9,
  GOLD_ORE: 10,
  GEM_ORE: 11,
  WATER: 12,
  BEDROCK: 13,
  COBBLE: 14,
  GLASS: 15,
  BRICK: 16,
  SNOW_TOP: 17,
  TORCH: 18,
  GRAVEL: 19,
  CRAFT_TOP: 20,
  CRAFT_SIDE: 21,
  CHEST_TOP: 22,
  CHEST_SIDE: 23,
  CHEST_FRONT: 24,
  TNT_SIDE: 25,
  TNT_TOP: 26,
  CACTUS_SIDE: 27,
  CACTUS_TOP: 28,
  CRACK_0: 29,
  CRACK_1: 30,
  CRACK_2: 31,
  CRACK_3: 32,
  CRACK_4: 33,
  LEAVES_SNOW: 34,
  MOSSY_COBBLE: 35,
  SANDSTONE: 36,
  SAND: 37,
  // mob skins (MO-1 … MO-3) — original 16×16 pixel patterns
  PIG: 38,
  PIG_HEAD: 39,
  COW: 40,
  COW_HEAD: 41,
  SHEEP: 42,
  SHEEP_HEAD: 43,
  ZOMBIE: 44,
  ZOMBIE_HEAD: 45,
  // faces carry the eyes and are mapped onto the front face of the head only
  PIG_FACE: 46,
  COW_FACE: 47,
  SHEEP_FACE: 48,
  ZOMBIE_FACE: 49,
  // first-person view model (VII)
  HAND: 50,
  SLEEVE: 51,
} as const;

export const CRACK_TILES = [
  TILE.CRACK_0,
  TILE.CRACK_1,
  TILE.CRACK_2,
  TILE.CRACK_3,
  TILE.CRACK_4,
];
